/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.96
 * Generated at: 2024-11-06 20:33:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import it.unibo.tw.web.beans.Catalogue;
import it.unibo.tw.web.beans.Cart;
import it.unibo.tw.web.beans.Item;
import java.util.List;

public final class cart_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


//AGGIUNGO AL CART
void add( Item item, Cart cart, int order) {
	boolean alreadyInCart = false;

	for ( Item articolo : cart.getItems() ) {  
		if ( articolo.getDescription().equals( item.getDescription() ) ) {
            alreadyInCart=true;
            //SE E' GIà PRESENTE NEL CARRELLO AGGIUNGO LA QUANTITA'
            order+=cart.getOrder(articolo);
            cart.put(item, order);
            break;
		}
	}
	
	if ( ! alreadyInCart) {
		cart.put(item, order);
	}
}

double total(Cart cart){
	double tot=0;
	for(Item it: cart.getItems()){
		//MOLTIPLICO PREZZO PER LA QUANTITà PRESENTE NEL CARRELLO
		tot+= it.getPrice()*cart.getOrder(it);
	}
	return tot;
}


  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/fragments/menu.jsp", Long.valueOf(1269278370000L));
    _jspx_dependants.put("/fragments/footer.jsp", Long.valueOf(1302173046000L));
    _jspx_dependants.put("/fragments/header.jsp", Long.valueOf(1302190716000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(6);
    _jspx_imports_classes.add("it.unibo.tw.web.beans.Catalogue");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("it.unibo.tw.web.beans.Cart");
    _jspx_imports_classes.add("it.unibo.tw.web.beans.Item");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"../errors/failure.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!-- pagina per la gestione di errori -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- accesso alla sessione -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- import di classi Java -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- metodi richiamati nel seguito -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- codice html restituito al client -->\r\n");
      out.write("<html>\r\n");
      out.write("	<head>\r\n");
      out.write("		<meta name=\"Author\" content=\"pisi79\">\r\n");
      out.write("		<title>Cart JSP</title>\r\n");
      out.write("		<link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/styles/default.css\" type=\"text/css\"/>\r\n");
      out.write("	</head>\r\n");
      out.write("\r\n");
      out.write("	<body>	\r\n");
      out.write("\r\n");
      out.write("		");
      out.write("<h1 id=\"header\">JSP project</h1>\n");
      out.write("\r\n");
      out.write("		");
      out.write("<div id=\"menu\">\n");
      out.write("	<ul id=\"tabs\">\n");
      out.write("		<li ");
      out.print( request.getRequestURI().contains("home") ? "style=\"background-color: #aaa;\"" : "");
      out.write(">\n");
      out.write("			<a href=\"");
      out.print( request.getContextPath() );
      out.write("/pages/home.jsp\">Home</a>\n");
      out.write("		</li>\n");
      out.write("		<li ");
      out.print( request.getRequestURI().contains("catalogue") ? "style=\"background-color: #aaa;\"" : "");
      out.write(">\n");
      out.write("			<a href=\"");
      out.print( request.getContextPath() );
      out.write("/pages/catalogue.jsp\">Manage catalogue</a>\n");
      out.write("		</li>\n");
      out.write("		<li ");
      out.print( request.getRequestURI().contains("cart") ? "style=\"background-color: #aaa;\"" : "");
      out.write(">\n");
      out.write("			<a href=\"");
      out.print( request.getContextPath() );
      out.write("/pages/cart.jsp\">Manage cart</a>\n");
      out.write("		</li>\n");
      out.write("		<li ");
      out.print( request.getRequestURI().contains("checkout") ? "style=\"background-color: #aaa;\"" : "");
      out.write(">\n");
      out.write("			<a href=\"");
      out.print( request.getContextPath() );
      out.write("/pages/checkout.jsp\">Checkout</a>\n");
      out.write("		</li>\n");
      out.write("	</ul>\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("		<div id=\"main\" class=\"clear\">\r\n");
      out.write("\r\n");
      out.write("			");
      it.unibo.tw.web.beans.Catalogue catalogue = null;
      synchronized (application) {
        catalogue = (it.unibo.tw.web.beans.Catalogue) _jspx_page_context.getAttribute("catalogue", javax.servlet.jsp.PageContext.APPLICATION_SCOPE);
        if (catalogue == null){
          catalogue = new it.unibo.tw.web.beans.Catalogue();
          _jspx_page_context.setAttribute("catalogue", catalogue, javax.servlet.jsp.PageContext.APPLICATION_SCOPE);
        }
      }
      out.write("\r\n");
      out.write("			");
      it.unibo.tw.web.beans.Cart cart = null;
      synchronized (session) {
        cart = (it.unibo.tw.web.beans.Cart) _jspx_page_context.getAttribute("cart", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (cart == null){
          cart = new it.unibo.tw.web.beans.Cart();
          _jspx_page_context.setAttribute("cart", cart, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write("\r\n");
      out.write("			\r\n");
      out.write("			");

					if ( request.getParameter("add") != null && request.getParameter("add").equals("aggiungi") ) {
						Item item = new Item();
						item.setDescription( request.getParameter("description") );
						item.setPrice( Double.parseDouble( request.getParameter("price") ) );
						item.setQuantity( Integer.parseInt(request.getParameter("quantity") ) );
						int num = Integer.parseInt(request.getParameter("order"));
						
						if(num < item.getQuantity())
						  add(item, cart , num);
						else 
							throw new Exception("Non ci sono abbastanza articoli!");
							
					}
			
      out.write("\r\n");
      out.write("				\r\n");
      out.write("			<div id=\"left\" style=\"float: left; width: 48%\">\r\n");
      out.write("\r\n");
      out.write("				<p>Current catalogue:</p>\r\n");
      out.write("				<table class=\"formdata\">\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th style=\"width: 31%\">Description</th>\r\n");
      out.write("						<th style=\"width: 31%\">Price</th>\r\n");
      out.write("						<th style=\"width: 31%\">Quantity</th>\r\n");
      out.write("						<th style=\"width: 7%\"></th>\r\n");
      out.write("					</tr>\r\n");
      out.write("					");
 
					Item[] items = catalogue.getItems().toArray(new Item[0]);
					for( Item anItem : items ){  
					
      out.write(" \r\n");
      out.write("					  <form>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td>");
      out.print( anItem.getDescription() );
      out.write("</td>\r\n");
      out.write("							<td>");
      out.print( anItem.getPrice() );
      out.write(" &#8364;</td>\r\n");
      out.write("							<td><input type=\"number\" name=\"order\" min=\"0\" step=\"1\"></td>\r\n");
      out.write("							<td>\r\n");
      out.write("							 <input type=\"hidden\" name=\"description\" value=\"");
      out.print( anItem.getDescription() );
      out.write("\"/>\r\n");
      out.write("							 <input type=\"hidden\" name=\"quantity\" value=\"");
      out.print( anItem.getQuantity() );
      out.write("\"/>\r\n");
      out.write("							 <input type=\"hidden\" name=\"price\" value=\"");
      out.print( anItem.getPrice() );
      out.write("\"/>\r\n");
      out.write("							  <input type=\"submit\" name=\"add\" value=\"aggiungi\" style=\"width:100%\"/>\r\n");
      out.write("							</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						</form>\r\n");
      out.write("					");
 } 
      out.write("\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td>&nbsp;</td>\r\n");
      out.write("						<td>&nbsp;</td>\r\n");
      out.write("						<td>&nbsp;</td>\r\n");
      out.write("						<td>&nbsp;</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("				</table>			\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("				<div id=\"right\" style=\"float: right; width: 48%; border-right: 1px solid grey\">\r\n");
      out.write("			\r\n");
      out.write("				<p>Carrello:</p>\r\n");
      out.write("				<table class=\"formdata\">\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th style=\"width: 33%\">Description</th>\r\n");
      out.write("						<th style=\"width: 33%\">Price</th>\r\n");
      out.write("						<th style=\"width: 33%\">Quantity</th>\r\n");
      out.write("					</tr>\r\n");
      out.write("					");
 
					Item[] cartItems = cart.getItems().toArray(new Item[0]);
					for( Item anItem : cartItems ){  
					
      out.write(" \r\n");
      out.write("						<tr>\r\n");
      out.write("							<td>");
      out.print( anItem.getDescription() );
      out.write("</td>\r\n");
      out.write("							<td>");
      out.print( anItem.getPrice() );
      out.write(" &#8364;</td>\r\n");
      out.write("							<td>");
      out.print( cart.getOrder(anItem) );
      out.write("</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("					");
 } 
      out.write("\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td>&nbsp;</td>\r\n");
      out.write("						<td>&nbsp;</td>\r\n");
      out.write("						<td>&nbsp;</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("				</table>\r\n");
      out.write("				<p>\r\n");
      out.write("				Totale: <span style=\"color: red;\">");
      out.print( total(cart) );
      out.write(" &#8364;</span>\r\n");
      out.write("				</p>\r\n");
      out.write("			</div>\r\n");
      out.write("		\r\n");
      out.write("		<div class=\"clear\">\r\n");
      out.write("				<p>&nbsp;</p>\r\n");
      out.write("			</div>	\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		");
      out.write("<div id=\"footer\">\n");
      out.write("	This is a sample footer. &copy; 2011.\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
