/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.96
 * Generated at: 2024-11-06 20:33:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import it.unibo.tw.web.beans.Catalogue;
import it.unibo.tw.web.beans.Item;
import java.util.List;

public final class catalogue_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


void add(Catalogue catalogue, Item item) {

	boolean alreadyInCatalogue = false;
	
	for ( Item itemInCatalogue : catalogue.getItems() ) {
		if ( itemInCatalogue.getDescription().equals( item.getDescription() ) ) {
			itemInCatalogue.setQuantity( itemInCatalogue.getQuantity() + item.getQuantity() );
			alreadyInCatalogue = true;
			break;
		}
	}
	if ( ! alreadyInCatalogue ) {
		catalogue.getItems().add( item );
	}
}

void remove(Catalogue catalogue, String description) {
	
	for ( int i = 0 ; i < catalogue.getItems().size() ; i++ ) {
		if ( catalogue.getItems().get(i).getDescription().equals(description) ) {
			catalogue.getItems().remove(i);
			break;
		}
	}
}

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/fragments/menu.jsp", Long.valueOf(1269278370000L));
    _jspx_dependants.put("/fragments/footer.jsp", Long.valueOf(1302173046000L));
    _jspx_dependants.put("/fragments/header.jsp", Long.valueOf(1302190716000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("it.unibo.tw.web.beans.Catalogue");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("it.unibo.tw.web.beans.Item");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"../errors/failure.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!-- pagina per la gestione di errori -->\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- accesso alla sessione -->\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- import di classi Java -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- metodi richiamati nel seguito -->\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- codice html restituito al client -->\n");
      out.write("<html>\n");
      out.write("	<head>\n");
      out.write("		<meta name=\"Author\" content=\"pisi79\">\n");
      out.write("		<title>Catalogue JSP</title>\n");
      out.write("		<link rel=\"stylesheet\" href=\"");
      out.print( request.getContextPath() );
      out.write("/styles/default.css\" type=\"text/css\"/>\n");
      out.write("	</head>\n");
      out.write("\n");
      out.write("	<body>	\n");
      out.write("\n");
      out.write("		");
      out.write("<h1 id=\"header\">JSP project</h1>\n");
      out.write('\n');
      out.write('	');
      out.write('	');
      out.write("<div id=\"menu\">\n");
      out.write("	<ul id=\"tabs\">\n");
      out.write("		<li ");
      out.print( request.getRequestURI().contains("home") ? "style=\"background-color: #aaa;\"" : "");
      out.write(">\n");
      out.write("			<a href=\"");
      out.print( request.getContextPath() );
      out.write("/pages/home.jsp\">Home</a>\n");
      out.write("		</li>\n");
      out.write("		<li ");
      out.print( request.getRequestURI().contains("catalogue") ? "style=\"background-color: #aaa;\"" : "");
      out.write(">\n");
      out.write("			<a href=\"");
      out.print( request.getContextPath() );
      out.write("/pages/catalogue.jsp\">Manage catalogue</a>\n");
      out.write("		</li>\n");
      out.write("		<li ");
      out.print( request.getRequestURI().contains("cart") ? "style=\"background-color: #aaa;\"" : "");
      out.write(">\n");
      out.write("			<a href=\"");
      out.print( request.getContextPath() );
      out.write("/pages/cart.jsp\">Manage cart</a>\n");
      out.write("		</li>\n");
      out.write("		<li ");
      out.print( request.getRequestURI().contains("checkout") ? "style=\"background-color: #aaa;\"" : "");
      out.write(">\n");
      out.write("			<a href=\"");
      out.print( request.getContextPath() );
      out.write("/pages/checkout.jsp\">Checkout</a>\n");
      out.write("		</li>\n");
      out.write("	</ul>\n");
      out.write("</div>");
      out.write("\n");
      out.write("	\n");
      out.write("		<div id=\"main\" class=\"clear\">\n");
      out.write("\n");
      out.write("			");
      it.unibo.tw.web.beans.Catalogue catalogue = null;
      synchronized (application) {
        catalogue = (it.unibo.tw.web.beans.Catalogue) _jspx_page_context.getAttribute("catalogue", javax.servlet.jsp.PageContext.APPLICATION_SCOPE);
        if (catalogue == null){
          catalogue = new it.unibo.tw.web.beans.Catalogue();
          _jspx_page_context.setAttribute("catalogue", catalogue, javax.servlet.jsp.PageContext.APPLICATION_SCOPE);
        }
      }
      out.write("\n");
      out.write("			\n");
      out.write("			");

				String description = request.getParameter("description");
	
				if ( description != null && ! description.equals("") ) {

					if ( description.contains(" ") ) {
						throw new Exception("Blanks are not allowed in the description field!"); 					
					}
					
					if ( request.getParameter("add") != null && request.getParameter("add").equals("submit item") ) {
						Item item = new Item();
						item.setDescription( description );
						item.setPrice( Double.parseDouble( request.getParameter("price") ) );
						item.setQuantity( Integer.parseInt(request.getParameter("quantity") ) );
						add(catalogue,item);
					}
					else if ( request.getParameter("remove") != null && request.getParameter("remove").equals("ok") ) {
						remove(catalogue,description);
					}
					
				}
			
      out.write("\n");
      out.write("			\n");
      out.write("			<div id=\"left\" style=\"float: left; width: 48%; border-right: 1px solid grey\">\n");
      out.write("			\n");
      out.write("				<p>Add an item to the catalogue:</p>\n");
      out.write("				<form>\n");
      out.write("					<table>\n");
      out.write("						<tr><td>\n");
      out.write("							<label for=\"desc\">Description:</label>\n");
      out.write("						</td><td>\n");
      out.write("							<input type=\"text\" name=\"description\"/>\n");
      out.write("						</td></tr>\n");
      out.write("						<tr><td>\n");
      out.write("							<label for=\"price\">Price (&#8364;):</label>\n");
      out.write("						</td><td>\n");
      out.write("							<input type=\"text\" name=\"price\"/>\n");
      out.write("						</td></tr>\n");
      out.write("						<tr><td>\n");
      out.write("							<label for=\"price\">Quantity:</label>\n");
      out.write("						</td><td>\n");
      out.write("							<input type=\"text\" name=\"quantity\"/>\n");
      out.write("						</td></tr>\n");
      out.write("						<tr><td colspan=\"2\">\n");
      out.write("							<input type=\"submit\" name=\"add\" value=\"submit item\" style=\"width:100%\"/>\n");
      out.write("						</td></tr>\n");
      out.write("					</table>\n");
      out.write("				</form>\n");
      out.write("		\n");
      out.write("			</div>\n");
      out.write("			\n");
      out.write("			<div id=\"right\" style=\"float: right; width: 48%\">\n");
      out.write("\n");
      out.write("				<p>Current catalogue:</p>\n");
      out.write("				<table class=\"formdata\">\n");
      out.write("					<tr>\n");
      out.write("						<th style=\"width: 31%\">Description</th>\n");
      out.write("						<th style=\"width: 31%\">Price</th>\n");
      out.write("						<th style=\"width: 31%\">Available quantity</th>\n");
      out.write("						<th style=\"width: 7%\"></th>\n");
      out.write("					</tr>\n");
      out.write("					");
 
					Item[] items = catalogue.getItems().toArray(new Item[0]);
					for( Item anItem : items ){  
					
      out.write(" \n");
      out.write("						<tr>\n");
      out.write("							<td>");
      out.print( anItem.getDescription() );
      out.write("</td>\n");
      out.write("							<td>");
      out.print( anItem.getPrice() );
      out.write(" &#8364;</td>\n");
      out.write("							<td>");
      out.print( anItem.getQuantity() );
      out.write("</td>\n");
      out.write("							<td>\n");
      out.write("								<a href=\"?remove=ok&description=");
      out.print( anItem.getDescription() );
      out.write("\">\n");
      out.write("								<img src=\"../images/remove.gif\" alt=\"remove\"/></a>\n");
      out.write("							</td>\n");
      out.write("						</tr>\n");
      out.write("					");
 } 
      out.write("\n");
      out.write("					<tr>\n");
      out.write("						<td>&nbsp;</td>\n");
      out.write("						<td>&nbsp;</td>\n");
      out.write("						<td>&nbsp;</td>\n");
      out.write("						<td>&nbsp;</td>\n");
      out.write("					</tr>\n");
      out.write("				</table>			\n");
      out.write("			</div>\n");
      out.write("		\n");
      out.write("			<div class=\"clear\">\n");
      out.write("				<p>&nbsp;</p>\n");
      out.write("			</div>\n");
      out.write("			\n");
      out.write("		</div>\n");
      out.write("	\n");
      out.write("		");
      out.write("<div id=\"footer\">\n");
      out.write("	This is a sample footer. &copy; 2011.\n");
      out.write("</div>");
      out.write("\n");
      out.write("\n");
      out.write("	</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
