/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.96
 * Generated at: 2024-11-20 17:27:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.contents;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import it.unibo.tw.web.beans.Feed;
import it.unibo.tw.web.beans.FeedDb;
import java.util.List;
import java.util.ArrayList;

public final class feed_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(6);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("it.unibo.tw.web.beans.FeedDb");
    _jspx_imports_classes.add("it.unibo.tw.web.beans.Feed");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"../errors/failure.jsp", false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<?xml version='1.0' encoding='ISO-8859-1'?>\n");
      out.write("\n");
      out.write("<!-- \n");
      out.write("NOTA BENE!!!  \n");
      out.write("Il PROLOGO XML deve SEMPRE essere collocato nella PRIMA RIGA!\n");
      out.write("Nessun carattere in output fino a questo momento!! \n");
      out.write("Usero' ora l'out della jsp per restituire l'xml che ajax si attende!!!!\n");
      out.write("\n");
      out.write("OSSERVATE IL TRAFFICO HTTP NEL TUNNEL!!!!!\n");
      out.write("-->\n");
      out.write("\n");
      out.write("<!-- pagina per la gestione di errori -->\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- accesso alla sessione -->\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- import di classi Java -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- librerie di terze parti -->\n");
      out.write("<!-- n.d. -->\n");
      out.write("\n");
      out.write("<!-- creazione Java Bean con scope di applicazione -->\n");
      it.unibo.tw.web.beans.FeedDb feedDb = null;
      synchronized (application) {
        feedDb = (it.unibo.tw.web.beans.FeedDb) _jspx_page_context.getAttribute("feedDb", javax.servlet.jsp.PageContext.APPLICATION_SCOPE);
        if (feedDb == null){
          feedDb = new it.unibo.tw.web.beans.FeedDb();
          _jspx_page_context.setAttribute("feedDb", feedDb, javax.servlet.jsp.PageContext.APPLICATION_SCOPE);
        }
      }
      out.write('\n');
      out.write('\n');


// QUESTO E' IMPORTANTISSIMO AFFINCHE' L'INTERPRETE JAVASCRIPT RICONOSCA IL CONTENUTO COME XML!!!!!!
response.setHeader("Content-Type","application/xml");


      out.write("\n");
      out.write("<!-- segue quindi il codice.... questa volta NON HTML!!!!! ... restituito al client -->\n");
      out.write("\n");
      out.write("<rss version='2.0'>\n");
      out.write("	<channel>\n");
      out.write("		<title><![CDATA[HomePage - LASTAMPA.it]]></title>\n");
      out.write("		<link>http://www.lastampa.it/redazione/</link>\n");
      out.write("		<description><![CDATA[lastampa.it - I titoli della Home Page]]></description>\n");
      out.write("		<lastBuildDate><![CDATA[Mon, 16 May 2011 15:58:35 +0200]]></lastBuildDate>\n");
      out.write("		<docs></docs>\n");
      out.write("		<managingEditor></managingEditor>\n");
      out.write("\n");
      out.write("		<webMaster>teleservizi s.r.l.</webMaster>\n");
      out.write("		<language>it-IT</language>\n");
      out.write("		<image>\n");
      out.write("  			<url>http://www.lastampa.it/common/images/lastampatop.gif</url> \n");
      out.write("  			<title>lastampa.it</title> \n");
      out.write("  			<link>http://www.lastampa.it/redazione/</link> \n");
      out.write("  			<width></width> \n");
      out.write("  			<height></height> \n");
      out.write("  		</image>\n");
      out.write("\n");


	// recupero il tipo di categoria cercata dai parametri della richiesta
	String category = request.getParameter("category");
	
	// recupero i feed corrispondenti da database
	List<Feed> someFeeds = feedDb.find(category);
	
	// li stampo su out
	for ( Feed feed : someFeeds ) {

      out.write("\n");
      out.write("		<item>\n");
      out.write("			<title><![CDATA[");
      out.print(feed.getTitle());
      out.write("]]></title>\n");
      out.write("			<description><![CDATA[");
      out.print(feed.getDescription());
      out.write("]]></description>\n");
      out.write("			<author><![CDATA[");
      out.print(feed.getAuthor());
      out.write("]]></author>\n");
      out.write("			<category><![CDATA[");
      out.print(feed.getCategory());
      out.write("]]></category>\n");
      out.write("			<pubDate><![CDATA[");
      out.print(feed.getPubDate());
      out.write("]]></pubDate>\n");
      out.write("			<link><![CDATA[");
      out.print(feed.getLink());
      out.write("]]></link>\n");

			if ( feed.getImageUrl() != null && feed.getImageUrl().length() > 0 ) {

      out.write("		\n");
      out.write("				<enclosure url='");
      out.print(feed.getImageUrl());
      out.write("' type='image/jpeg' />\n");
 
			}

      out.write("		\n");
      out.write("		</item>\n");
 
	}

      out.write("\n");
      out.write("\n");
      out.write("	</channel>\n");
      out.write("</rss>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
