/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.96
 * Generated at: 2024-12-19 10:17:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.google.gson.Gson;
import java.util.*;
import Beans.*;

public final class j2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(7);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("Beans");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.google.gson.Gson");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("  <title>J2 Page</title>\n");
      out.write(" <link type=\"text/css\" href=\"styles/default.css\" rel=\"stylesheet\"></link>\n");
      out.write("        <script type=\"text/javascript\" src=\"scripts/utils.js\"></script>\n");
      out.write("        <script type=\"text/javascript\" src=\"scripts/split.js\"></script>\n");
      out.write(" </head>\n");
      out.write("<body>\n");
      out.write("   <div>\n");
      out.write("       ");
  // String prod1 = (String) this.getServletContext().getAttribute("prodotto");
            HashMap<String, String> prod = (HashMap<String, String>) this.getServletContext().getAttribute("prodottoAsta");
            Gson g = new Gson();
            User u = (User) session.getAttribute("currentUser");

            String pr = prod.get(u.getId());
            
            //Prodotto p = prod.get(u.getId());
            
            System.out.println("prodotto: "+prod);
            
            Map<String, User> vincite = new HashMap<String, User>();
            
            Prodotto p = new Prodotto();
			
			
            //MI PRENDO UTENTE E IL PRODOTTO
            if(u!=null && pr!=null){
            	
             //TANTO PER LO STESSO PRODOTTO MI SOVRASCRVE FINO ALL'ULTIMO CHE SCRIVE CHE
             //SARà IL VINCITORE
              p = g.fromJson(pr , Prodotto.class);
    		  vincite.put(p.getNome(), u);

           
      out.write("\n");
      out.write("             <h3> NOME OGGETTO:</h3> ");
      out.print(p.getNome() );
      out.write("<br>\n");
      out.write("             <h3> DESCRIZIONE:</h3> ");
      out.print(p.getDescription() );
      out.write("<br>\n");
      out.write("             <h3> PREZZO BASE:</h3> ");
      out.print(p.getPrice() );
      out.write("<br>\n");
      out.write("              \n");
      out.write("              <form id=\"MyForm\" action=\"servlet1\" method=\"post\">\n");
      out.write("              <input type=\"text\" id=\"utente\" style=\"display:none\" name=\"vincitore\" value=\"");
      out.print(u.getUserName());
      out.write("\" >\n");
      out.write("              <input type=\"text\" id=\"rimasti\" style=\"display:none\" value=\"");
      out.print(u.getDenari());
      out.write("\">\n");
      out.write("              <input type=\"text\" id=\"prezzobase\" style=\"display:none\" value=\"");
      out.print(p.getPrice());
      out.write("\">\n");
      out.write("              <input type=\"text\" id=\"vinto\" style=\"display:none\">\n");
      out.write("              <label>Inserisci offerta: </label><br>\n");
      out.write("              <input type=\"number\" id=\"fl1\" min=\"");
      out.print(p.getPrice());
      out.write("\" onkeyup=\"controllo()\">\n");
      out.write("              </form>\n");
      out.write("              \n");
      out.write("              \n");
      out.write("  		      \n");
      out.write("            ");

            Catalogo c = (Catalogo) this.getServletContext().getAttribute("catalogo"); 
		      c.remove(p);
		      this.getServletContext().setAttribute("catalogo", c); 
            }
  		       
  		       
               String errore = (String) this.getServletContext().getAttribute("errore");
               Integer er=null;
               
               if(errore!=null)
                 er = Integer.parseInt(errore);
               
               if( er != null && er==1){
           
      out.write("\n");
      out.write("               <p>FINITI I PRODOTTI NEL CATALOGO</p>\n");
      out.write("            ");
 }
            
       
      out.write("\n");
      out.write("    </div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
